### ISSUE TITLE
Get robot model to work in simulation on cluster

### ISSUE THREAD

**Issue by CrunchyFlakes** [LUH-AI/robotics-project-24#11]
Get [Go2 IsaacLab Repo](https://github.com/abizovnuralem/go2_omniverse/) to work on cluster.

**Comment by ThorKlm** [comment]
IsaacGym and unitree_rl_gym setup to get the go2 robot model to work and get trained in a simulation on cluster.
Note: IsaacGym is now used since IsaacLab only worked locally and is still not running on the cluster. IsaacSim, however seems to run on the cluster.
